# Exported from:        http://localhost:5516/
# Release version:      24.3.0-1009.113
# Date created:         Fri Oct 11 11:16:46 GMT 2024

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: Workflow Executions
  home: Digital.ai - Official/Workflow Executions
spec:
- directory: "."
  teams:
  - name: Template Owner
    permissions:
    - template#edit_failure_handler
    - template#edit_precondition
    - template#lock_task
  - name: Workflow Admin
    roles:
    - Authenticated Users
    permissions:
    - folder#view
    - workflow#start_execution
  - name: Release Admin
    permissions:
    - release#edit_failure_handler
    - release#edit_precondition
    - release#lock_task
  - name: Folder Owner
