# Exported from:        http://localhost:5516/
# Release version:      24.1.0-216.113
# Date created:         Fri Feb 16 11:11:55 GMT 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Permissions.yaml
  - "Workflow_Create, update, or destroy infrastructure in the cloud using Terraform.yaml"
