# Exported from:        http://localhost:5516/
# Release version:      24.3.0-1009.113
# Date created:         Wed Oct 09 12:48:28 GMT 2024

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: Templates
  home: Digital.ai - Official/Templates
spec:
- directory: "."
  teams:
  - name: Template Owner
    permissions:
    - template#edit_failure_handler
    - template#edit_precondition
    - template#lock_task
  - name: Folder Owner
  - name: Viewer
    roles:
    - Authenticated Users
    permissions:
    - folder#view
    - release#start
    - release#view
    - template#create_release
    - template#view
  - name: Release Admin
    permissions:
    - release#edit_failure_handler
    - release#edit_precondition
    - release#lock_task
