# Exported from:        http://localhost:5516/
# Release version:      24.1.0-216.113
# Date created:         Fri Feb 16 11:11:54 GMT 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Permissions.yaml
  - Workflow_Delete Application in ArgoCD.yaml
  - Workflow_Install Argo Rollouts.yaml
  - Workflow_Install ArgoCD.yaml
  - Workflow_Setup ArgoCD application with initial deployment.yaml
