# Exported from:        http://localhost:5516/
# Release version:      24.3.0-1009.113
# Date created:         Fri Oct 11 11:16:45 GMT 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Workflows/Digital.ai Deploy
  home: Digital.ai - Official/Workflows/Digital.ai Deploy
spec:
- template: Deploy delete application
  scheduledStartDate: 2023-04-27T13:00:00Z
  dueDate: 2023-04-27T14:00:00Z
  phases:
  - phase: Delete Application in Deploy
    tasks:
    - name: Get configuration details
      type: xlrelease.ScriptTask
      description: Getting configuration details of the target deployment server.
      script: |-
        from com.xebialabs.xlrelease.domain.environments import LiveDeployment

        liveDeployment = deploymentServerApi.getLiveDeployment("${liveDeploymentId}")
        statusWebhookEventSource = configurationApi.getConfiguration(liveDeployment.eventSourceId)

        applicationName = liveDeployment.getApplication().getTitle()
        environmentName = liveDeployment.getEnvironment().getTitle()
        environmentPath = liveDeployment.getEnvironment().getDeploymentTarget().getProperty("environmentPath")
        environmentCiId = environmentPath.split("ciId=")[-1] if "ciId=" in environmentPath else ""

        releaseVariables['statusWebhookEventSourceId'] = statusWebhookEventSource.id
        releaseVariables['deployedApplication'] = environmentCiId + "/" + applicationName
        releaseVariables['applicationName'] = applicationName
        releaseVariables['environmentName'] = environmentName
        releaseVariables['server'] = statusWebhookEventSource["sourceServer"].id
    - name: Application details
      type: xlrelease.UserInputTask
      description: |-
        Please enter the application you want to delete.

        The application will also be undeployed
      variables:
      - server
      - deployedApplication
    - name: Undeploy application in Deploy
      type: deploy.Undeploy
      description: "Undeploying **${deployedApplication}**"
      variableMapping:
        server: "${server}"
      capabilities:
      - remote
      deployedApplication: "${deployedApplication}"
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    - name: Delete configuration
      type: xlrelease.ScriptTask
      description: Deleting  configuration from Digital.ai Release
      script: |-
        statusWebhookEventSource = configurationApi.getConfiguration("${statusWebhookEventSourceId}")
        liveDeploymentConfigs = statusWebhookEventSource.getProperty("liveDeploymentConfigs")

        applicationName = "${applicationName}"
        environmentName = "${applicationName}"

        configToDelete = None
        for config in liveDeploymentConfigs:
            if config.getProperty("application") == applicationName and config.getProperty("environment") == environmentName:
                configToDelete = config
                break

        if configToDelete:
            liveDeploymentConfigs.remove(configToDelete)
            statusWebhookEventSource.setProperty("liveDeploymentConfigs", liveDeploymentConfigs)
            configurationApi.updateConfiguration("${statusWebhookEventSourceId}", statusWebhookEventSource)
            configurationApi.deleteConfiguration(configToDelete.id)
    color: "#3d6c9e"
  kind: WORKFLOW
  tags:
  - Remote Deploy
  - application
  - delete
  categories:
  - Application onboarding
  variables:
  - type: xlrelease.StringVariable
    key: liveDeploymentId
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: statusWebhookEventSourceId
    requiresValue: false
    showOnReleaseStart: false
  - type: xlrelease.StringVariable
    key: deployedApplication
    requiresValue: false
    showOnReleaseStart: false
    label: Deployed Application
    description: "Full name of the deployed application, e.g. Environments/ProdEnv/PetClinic"
  - type: xlrelease.ReferenceVariable
    key: server
    requiresValue: false
    showOnReleaseStart: false
    label: Deploy server
    description: Deploy server connection details
    referencedType: digitalai.DeployServer
  - type: xlrelease.StringVariable
    key: applicationName
    requiresValue: false
    showOnReleaseStart: false
    label: Application Name
  - type: xlrelease.StringVariable
    key: environmentName
    requiresValue: false
    showOnReleaseStart: false
    label: Environment Name
  disableNotifications: true
  author: Digital.ai
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/png
    file: !file "template-logo/7419b7fc52c2ab01411b0e4b9b954dd3ca79c2db/deploy.svg"
  defaultTargetFolder: Digital.ai - Official/Workflow Executions
