# Exported from:        http://localhost:5516/
# Release version:      24.3.0-1009.113
# Date created:         Wed Oct 09 12:48:29 GMT 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
  - Workflow_CheckmarxOne scan Git repository.yaml
