# Exported from:        http://localhost:5516/
# Release version:      24.3.0-1009.113
# Date created:         Fri Oct 11 11:16:46 GMT 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
  - Workflow_List Azure Container Registry Images.yaml
