---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  home: Digital.ai - Official/Workflows
spec:
- directory: "."
  teams:
  - name: Viewer
    roles:
    - Authenticated Users
    permissions:
    - template#view
    - folder#view
  - name: Template Owner
  - name: Folder Owner
  - name: Release Admin
