# Exported from:        http://localhost:5516/
# Release version:      24.3.0-1009.113
# Date created:         Wed Oct 09 13:29:33 GMT 2024

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: /
  home: Digital.ai - Official
spec:
- directory: "."
  teams:
  - name: Release Admin
    permissions:
    - release#edit_failure_handler
    - release#edit_precondition
    - release#lock_task
  - name: Template Owner
    permissions:
    - template#edit_failure_handler
    - template#edit_precondition
    - template#lock_task
  - name: Folder Owner
  - name: Viewer
    roles:
    - Authenticated Users
    permissions:
    - folder#view
