---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
    - Workflow_Install additional Remote Runner in Kubernetes.yaml
    - Workflow_Install Remote Runner in Kubernetes.yaml
    - Workflow_Install Remote Runner with Digital.ai Cloud Connector.yaml
