---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Workflow_Install additional Remote Runner onto existing Kubernetes cluster with an existing Remote Runner.yaml
  - Workflow_Install Remote Runner onto existing Kubernetes cluster.yaml
  - Workflow_Install Remote Runner and embedded Kubernetes cluster using Digital.ai Platform.yaml
