---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Digital.ai - Official/Workflows/Remote Runner
spec:
  - template: Install Remote Runner in Kubernetes
    description: Install a Remote Runner into an existing Kubernetes cluster using the
      `xl` client.
    scheduledStartDate: 2023-12-22T09:00:00+01:00
    dueDate: 2023-12-22T10:00:00+01:00
    phases:
      - phase: Workflow tasks
        tasks:
          - name: Set up Kubernetes cluster
            type: xlrelease.Task
            description: |-
              Configure Kubernetes cluster
              
              Current supported clusters:
              - Openshift
              - AWS EKS
              - Plain multi-node K8s cluster
              - Azure AKS
              - Google Kubernetes Engine
              
              Also, `kubectl` should be up and running and connected to the cluster
          - name: Create user and token for Remote Runner registration
            type: xlrelease.Task
            description: |-
              ### Create Remote Runner user and assign permissions
              
              * Create a new user `remote-runner`
              * Create a global role **Remote Runners** with the remote runner user in it
              * Assign global permission **Runner registration** to the Remote Runners role
              
              ### Create access token
              
              * Login as `remote-runner`
              * Go to the **Access tokens** page in the user menu (top right corner)
              * Create a new token called **Remote Runner token** and copy it into the Remote Runner token field below
          - name: Install XL CLI
            type: xlrelease.Task
            description: |-
              [About XL CLI](https://docs.digital.ai/bundle/devops-release-version-v.23.3/page/release/operator/xl-op-before-you-begin.html)
              
              [Instructions to install XL CLI](https://docs.digital.ai/bundle/devops-deploy-version-v.23.3/page/deploy/how-to/install-the-xl-cli.html)
              
              Make sure that you run the same version of `xl` as the installation of Digital.ai Release
          - name: Install Remote Runner
            type: xlrelease.Task
            description: |-
              ## Install new Remote Runner through XL CLI
              
              Run `xl kube install`
              
              This will start a CLI wizard.
              
              ### Remote Runner install wizard
              - Insert kubectl context to be used during execution (or use default)
              - Select Kubernetes setup
              - Insert Kubernetes namespace (or use default)
              - When be asked to select a product for installation, select `dai-release-remote-runner [Remote Runner for Digital.ai Release]`
              - Select type of image registry (or use default)
              - Enter Remote Runner image information (or use default)
              - Enter Remote Runner Helm Chart release name and version (or use default)
              - Enter the URL for the Digital.ai Release server that is **reachable from within the Kubernetes cluster**
              - Enter token from previous step
              - Enter how many replicas of Remote Runner you want
              
              
              To customize the configuration based on your setup, `xl kube install` offers various customization options. Please refer to the [documentation](https://docs.digital.ai/bundle/devops-release-version-v.23.3/page/release/operator/xl-op-before-you-begin.html) for further information
    kind: WORKFLOW
    categories:
      - Remote Runner installation
    disableNotifications: true
    author: admin
    defaultTargetFolder: Digital.ai - Official/Workflow Executions
